apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass

metadata:
  name: default

spec:
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  role: project6-dev-node-role

  subnetSelectorTerms:
    - tags:
        kubernetes.io/cluster/project6-dev: shared

  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/project6-dev: owned
